version: 2.1
orbs:
  node: circleci/node@1.1.6
jobs:
  test_coverage:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run: npm run test:coverage

  build:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - checkout
      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "package.json" }}
            - v1-dependencies-
      - run: npm ci
      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}
      - run:
          name: Build Source
          command: npm run build
      - persist_to_workspace:
          root: ~/repo
          paths: .

  deploy:
    docker:
      - image: circleci/node:12.16.1
    working_directory: ~/repo
    steps:
      - attach_workspace:
          at: ~/repo
      - run:
          name: Delete Readme
          command: unlink  ~/repo/README.md
      - run:
          name: Copy Smaller Readme
          command: cp  ~/repo/README.npm.md ~/repo/README.md
      - run:
          name: Authenticate with NPM
          command: echo "//registry.npmjs.org/:_authToken=$NPM_TOKEN" > ~/repo/.npmrc
      - run:
          name: Publish package
          command: npm publish

workflows:
  version: 2
  develop_commit:
    jobs:
      - test_coverage:
          filters:
            branches:
              only: /develop/
  master_commit:
    jobs:
      - build:
          filters:
            branches:
              only: /master/
      - deploy:
          filters:
            branches:
              only: /master/
          requires:
            - build
